### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Biaocsu** [algolet/question_generation#1]
您好，我这边qg任务运行时，训练阶段无问题，训练结束后在**验证阶段**会出现莫名报错，请问有可能知道原因在哪吗？希望您有时间能帮忙分析下，不甚感激

```
[INFO|trainer.py:2243] 2022-04-16 13:53:18,863 >> ***** Running Evaluation *****
[INFO|trainer.py:2245] 2022-04-16 13:53:18,863 >>   Num examples = 2848
[INFO|trainer.py:2248] 2022-04-16 13:53:18,863 >>   Batch size = 16
Traceback (most recent call last):
  File "run_qg.py", line 578, in <module>
    main()
  File "run_qg.py", line 528, in main
    metrics = trainer.evaluate(max_length=max_length, num_beams=num_beams, metric_key_prefix="eval")
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer_seq2seq.py", line 75, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 2113, in evaluate
    output = eval_loop(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 2285, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer_seq2seq.py", line 174, in prediction_step
    generated_tokens = self.model.generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation_utils.py", line 907, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation_utils.py", line 416, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(input_ids, return_dict=True, **encoder_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 904, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2173, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by Vivicai1005** [comment]
你好，我这边没有复现这个问题。你可以在代码中检查一下在evaluation的时候，模型和eval_dataset是否同时在指定的gpu卡上。

**Comment by Biaocsu** [comment]
我是根据您的代码来运行的，如果您复现没问题，那有可能是我多GPU机器设置等问题。另外，您方便将预测代码开源下吗？我检查项目没看到预测部分逻辑，多谢哈。如果不方便完全开源，是否可以发邮箱小范围让我学习借鉴下，多谢
邮箱：liubiaocsu@163.com

**Comment by Vivicai1005** [comment]
你说的是模型推理代码吗？模型推理代码在question_generation/pipelines/question_generation.py这里。训练run_qg.py文件里面这里

      `if training_args.do_predict:
             logger.info("*** Predict ***")

        predict_results = trainer.predict(
            predict_dataset, metric_key_prefix="predict", max_length=max_length, num_beams=num_beams
        )`
开始都是预测代码。可以设置do_predict为true，这样训练完可以跑测试集的推理。

**Comment by Biaocsu** [comment]
好的，我先把代码调通再看下。我是看到readme中有这样的调用形式，然后在代码中没找到该部分逻辑。多谢哈

```
>>> from question_generation import pipeline

# Allocate a pipeline for question-generation
# cpu版本, 如果不传入device参数，默认是cpu版本，
>>> qg = pipeline("question-generation", device="cpu") 
# gpu版本
>>> qg = pipeline("question-generation", device="cuda") 
```

**Comment by Biaocsu** [comment]
您好，我想问下您当时训练QG任务时，您的显卡显存多大，我看您

**Comment by chenzebiaohub** [comment]
@Biaocsu 您好 我也是做QG方向的研究，可惜我要进行训练无法运行成功，能请教一下您？
ValueError: Some keys are not used by the HfArgumentParser: ['model_type']
